// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrphdocrnjffrlvagsxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlycGhkb2NybmpmZnJsdmFnc3h1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYwOTkyNzksImV4cCI6MjA1MTY3NTI3OX0.Z4HUqDSmv8aW2Uou1kab-fyXkVU47PHCXw7QRKBcwAo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);